---
deployment:
  tasks:
    - export DEPLOYPATH=/home/funtofu/public_html/apify-etl/
    - /opt/cpanel/ea-nodejs10/bin/npm install
    - /usr/bin/rsync -a --exclude '.git' --exclude .gitignore . $DEPLOYPATH